<?php
/**
 * Storelocator template for stores list
 */
?>
<?php
$markers = array();
?>
<div class="page-title">
    <h1><?php echo Mage::helper('archana_storelocator')->__('Store Locator') ?></h1>
</div>
<table border="0" id="search-store">
    <tr>
        <td style="width: 45%">
            <form action="<?php echo $this->getPostActionUrl() ?>" method="get" id="addressSearch">
                <div class="fieldset">
                    <h2 class="legend">Search Store</h2>
                    <ul class="form-list store-list">
                        <?php
                        $_continent = Mage::getModel('archana_storelocator/storelocator')->getCollection()
                                ->addFieldToFilter('status', 1);
                        $_continent->getSelect()->group('continent');
                        ?>
                        <li>
                            <label for="continent"><?php echo $this->__('Continent') ?></label>
                            <div class="input-box">
                                <select name="continent" id="continent" class="select" title="<?php echo $this->__('Continent') ?>">
                                    <option value=""><?php echo $this->__('-- Please Select --'); ?></option>
                                    <?php foreach ($_continent as $_continent): ?>
                                        <option value="<?php echo $_continent->getContinent() ?>" 
                                                <?php if ($this->getFormData()->getContinent() == $_continent->getContinent()): ?>selected="selected"<?php endif; ?>>
                                                    <?php echo $_continent->getContinent() ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </li>


                        <?php $_countries = $this->getCountries(); ?>
                        <?php if (count($_countries) > 0): ?>
                            <li id="countryNameDiv">
                                <label for="country"><?php echo $this->__('Country') ?></label>
                                <div class="input-box" id="countryData">
                                    <select name="country" id="country" class="select" title="<?php echo $this->__('Country') ?>">
                                        <option value=""><?php echo $this->__('-- Please Select --'); ?></option>
                                        <?php foreach ($_countries as $_country): ?>
                                            <option value="<?php echo $_country['value'] ?>" 
                                                    <?php if ($this->getFormData()->getCountry() == $_country['value']): ?>selected="selected"<?php endif; ?>>
                                                        <?php echo $_country['label'] ?>
                                            </option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                            </li>
                        <?php endif; ?>
                        <li>
                            <button type="submit" title="<?php echo $this->__('Search') ?>" class="button"><span><span><?php echo $this->__('Search') ?></span></span></button>
                            <button type="reset" title="<?php echo $this->__('Reset') ?>" class="button" onClick="setLocation('<?php echo Mage::getUrl('*/*/index') ?>')"><span><span><?php echo $this->__('Reset') ?></span></span></button>
                        </li>
                    </ul>
                </div>
            </form>
        </td>
    </tr>
</table>
<?php
$_StoreCollection = $this->getStoreCollection();
$i = 1;
$totalStoreCount = $_StoreCollection->count();
?>
<div class="your-store-title">
    <?php echo Mage::helper('archana_storelocator')->__('Your Stores') ?>
</div>
<?php $file_path = $_SERVER['PHP_SELF'];
    $pos_str = strpos($file_path, 'search');
    if ($pos_str === false) {
        $strName = "display: none;";
    } else {
        $strName = "display: block;";
    }
?>
<div id="stores-list-div" style="<?php echo $strName;?>">
    <table border="0" id="stores">
        <?php if (!$totalStoreCount): ?>
            <tr>
                <td><p class="note-msg"><?php echo $this->__('There are no stores.') ?></p></td>
            </tr>
        <?php else: ?>
            <tr>
                <?php foreach ($_StoreCollection as $store): ?>
                    <td valign="top" class="stores-view">
                        <table id="stores-inner">
                            <tr><td class="stores-name"><a href="<?php echo $this->getStoreUrl($store); ?>"><?php echo $this->escapeHtml(ucfirst($store->getName())) ?></a></td></tr>
                            <tr>
                                <td>
                                    <!-- country -->
                                    <?php if ($store->getCountry()): ?>
                                        <?php echo ucfirst($this->getCountryName($store->getCountry())); ?><br>
                                    <?php endif; ?>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <!-- State -->
                                    <?php if ($store->getState()): ?>
                                        <?php echo $this->escapeHtml(ucfirst($store->getState())); ?><br>
                                    <?php endif; ?>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <!-- City -->
                                    <?php if ($store->getCity()): ?>
                                        <?php echo $this->escapeHtml(ucfirst($store->getCity())); ?><br>
                                    <?php endif; ?>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <!-- Store Address -->
                                    <?php if ($store->getStreetAddress()): ?>
                                        <?php echo $this->escapeHtml($store->getStreetAddress()) ?><br>
                                    <?php endif; ?>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <!-- Zip Code -->
                                    <?php if ($store->getZipcode()): ?>
                                        Zip Code:<?php echo $this->escapeHtml($store->getZipcode()) ?><br>
                                    <?php endif; ?>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <!-- Phone -->
                                    <?php if ($store->getPhone()): ?>
                                        Phone:<?php echo $this->escapeHtml($store->getPhone()) ?><br>
                                    <?php endif; ?>
                                </td>
                            </tr>
                            <tr><td>&nbsp;</td></tr>
                            <tr>
                                <td>
                                    <table>
                                        <tr>
                                            <td>
                                                <button onclick="setLocation('<?php echo $this->getStoreUrl($store); ?>');" class="button" title="<?php echo Mage::helper('archana_storelocator')->__('View Details') ?>" type="button">
                                                    <span>
                                                        <span>
                                                            <?php echo Mage::helper('archana_storelocator')->__('View Details') ?>
                                                        </span>
                                                    </span>
                                                </button>
                                            </td>

                                            <td width="1px">&nbsp;</td>
                                            <td>
                                                <?php
                                                //Get store google map related information
                                                $storeName = $store->getName();
                                                $storeLat = $store->getLatitude();
                                                $storeLong = $store->getLongitude();
                                                $storeRadius = $this->getRadius($store);
                                                $storeZoomLevel = $this->getZoomLevel($store);
                                                ?>
                                                <?php if ($storeLat && $storeLong): ?>
                                                    <button onclick="initialize(<?php echo $storeLat; ?>, <?php echo $storeLong; ?>, <?php echo $storeRadius; ?>, <?php echo $storeZoomLevel; ?>, '<?php echo $storeName; ?>', 'store-list-map-canvas');" class="button" title="<?php echo Mage::helper('archana_storelocator')->__('View Map') ?>" type="button">
                                                        <span>
                                                            <span>
                                                                <?php echo Mage::helper('archana_storelocator')->__('View Map') ?>
                                                            </span>
                                                        </span>
                                                    </button>
                                                <?php endif; ?>
                                            </td>
                                        </tr>
                                    </table>

                                </td>
                            </tr>
                        </table>
                    </td>
                    <?php if ($i++ % 2 == 0) : ?>
                    </tr><tr> 
                    <?php endif; ?>
                    <?php
                    // for google map
                    $markers[$i]['name'] = $store->getName();
                    $markers[$i]['lat'] = $store->getLatitude();
                    $markers[$i]['long'] = $store->getLongitude();
                    ?>
                <?php endforeach; ?>
            <?php endif; ?>
        </tr> 
        <tr>
            <td align="right">&nbsp;</td>
        </tr>
        <tr>
            <td align="right" colspan="3"><?php echo $this->getPager() ?></td>
        </tr>
    </table>
</div>
<?php if ($totalStoreCount): ?>
    <div id="stores-list-gmap-div">
        <div id="store-list-map-canvas">&nbsp;</div>
    </div>
    <?php if (is_array($markers) && count($markers) > 0) : ?>
        <script>
            //<![CDATA[
            var markers = [
        <?php foreach ($markers as $marker) : ?>
                    ['<?php echo $marker['name']; ?>',<?php echo $marker['lat']; ?>,<?php echo $marker['long']; ?>],
        <?php endforeach ?>
            ];
            //]]>
        </script>
    <?php endif ?>
    <div id="show-all-store">
        <button onclick="place_multiple_markers(markers, googleMapDivId);" class="button" title="<?php echo Mage::helper('archana_storelocator')->__('Show All Stores') ?>" type="button">
            <span>
                <span>
                    <?php echo Mage::helper('archana_storelocator')->__('Show All Stores') ?>
                </span>
            </span>
        </button>
    </div>
    <script type="text/javascript">
        //<![CDATA[
        var addressSearch = new VarienForm('addressSearch', true);
        //]]>
    </script>
    <script>
        //<![CDATA[
        var googleMapDivId = 'store-list-map-canvas';
        google.maps.event.addDomListener(window, 'load', place_multiple_markers(markers, googleMapDivId));
        //]]>
    </script>
    <script type="text/javascript">
        (function ($) {
            $('#continent').change(function () {
                var firstDropVal = $('#continent').val();
                var commentUrl = "<?php echo Mage::getBaseUrl() . 'storelocator/index/getCountryBasedContinent/'; ?>";
                $.ajax({
                    type: "POST",
                    data: '&continent_name=' + firstDropVal,
                    dataType: "html",
                    url: commentUrl,
                    success: function (response) {
                        if (response.status = "SUCCESS") {
                            $('#countryData').html(response);
                        } else {
                            alert('error');
                        }
                    }

                });
            });

       })(jQuery);
        // This will disable all the children of the div

    </script>
    <?php




 endif ?>